name: Build and Deploy to Kubernetes Cluster
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wise-cow:latest
      
      - name: Update Kubernetes Deployment
        run: |
            kubectl -n wisecow set image deployment/wisecow wisecow=saddocker419/wise-cow:latest --record
            kubectl -n wisecow rollout status deployment/wisecow
